# Generated by Django 3.2.3 on 2022-07-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve_Month', models.IntegerField()),
                ('solve_Day', models.IntegerField()),
                ('solve_Year', models.IntegerField()),
                ('solve_Date', models.DateField()),
                ('solve_Player', models.CharField(max_length=50)),
                ('solve_Time', models.DurationField(null=True)),
                ('solve_Seconds', models.IntegerField(null=True)),
            ],
        ),
    ]
